# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfUZQ64XSLPBI0hAobVcy5CqwKVOyXrj
"""

!pip install mpld3


import pandas as pd
import matplotlib.pyplot as plt
import mpld3

file_path = '/content/Adri.csv'
data = pd.read_csv(file_path)

data.columns = ['Nombre Jugadora', 'Equipo', 'Edad']

data['Edad'] = pd.to_numeric(data['Edad'], errors='coerce')
print(data.head())

# Crear y guardar el gráfico de barras
plt.figure(figsize=(20, 15))
plt.bar(data['Nombre Jugadora'], data['Edad'], color='skyblue')
plt.xlabel('Jugadora')
plt.ylabel('Edad')
plt.title('Distribución de Edades de las Jugadoras de Fútbol Femenino Chileno en los Juegos Panamericanos 2023')
plt.xticks(rotation=90)

# Guardar como imagen
plt.savefig('/content/distribucion_edades.jpg')

# Mostrar el gráfico
plt.show()

html_fig = mpld3.fig_to_html(fig)
with open('/content/distribucion_edades.html', 'w') as f:
    f.write(html_fig)